load("@npm//jest-cli:index.bzl", _jest_test = "jest_test")

def jest_test(name, tests, deps, jest_config, **kwargs):
    "A macro around the autogenerated jest_test rule"
    args = [
        "--no-cache",
        "--no-watchman",
        "--ci",
    ]

    args.extend(["--config", "$(location %s)" % jest_config])

    for test in tests:
        args.extend(["--runTestsByPath", "$(locations %s)" % test])

    _jest_test(
        name = name,
        data = [jest_config] + tests + deps,
        args = args,
        **kwargs
    )
