load("@npm//jest-cli:index.bzl", _jest_test = "jest_test")

def jest_test(name, tests = [], jest_config = None, data = [], **kwargs):
    "A macro around the autogenerated jest_test rule"
    args = [
        "--no-cache",
        "--no-watchman",
        "--ci",
    ]

    if jest_config:
        args.extend(["--config", "$(location %s)" % jest_config])

    for test in tests:
        args.extend(["--runTestsByPath", "$(locations %s)" % test])

    data = data[:] + tests
    if jest_config:
        data += [jest_config]

    _jest_test(
        name = name,
        args = args,
        data = data,
        **kwargs
    )
