load("@npm//typescript:index.bzl", _tsc = "tsc")

def tsc(name, srcs, ts_config, deps, **kwargs):
    "A macro around the autogenerated tsc rule"
    outs = [f[:-3] + ".js" for f in srcs] + [f[:-3] + ".d.ts" for f in srcs]

    _tsc(
        name = name,
        outs = outs,
        args = [
            "-p",
            "$(location %s)" % ts_config,
            "--outDir",
            # $(RULEDIR) is a shorthand for the dist/bin directory where Bazel requires we write outputs
            "$(RULEDIR)",
        ],
        data = srcs + [ts_config] + deps
    )
